
#type: args

train:
  epochs: 500
  batch_size: 32
  lr: 1.0e-3

diffusion:
  layers: 4 
  channels: 64
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.001
  beta_end: 0.05 # 0.01~0.05
  num_steps: 500
  schedule: "quad"


